#!/bin/bash
# Azure Cleanup & Fix Script
# This will fix all the issues found in the diagnostic

set -e

RG_NAME="auditapp-staging-rg"

echo "=========================================="
echo "Azure Audit App - Cleanup & Fix"
echo "=========================================="
echo ""

echo "🔍 Issues Found:"
echo "1. ❌ Duplicate backend Container App (auditapp-backend)"
echo "2. ❌ Redis Cache deployed ($75/month - not used)"
echo "3. ❌ Key Vault deployed ($1/month - not used)"
echo "4. ❌ Static Web App not connected to GitHub"
echo "5. ❌ Old frontend Docker image in ACR"
echo ""

read -p "Do you want to proceed with cleanup? (yes/no): " CONFIRM
if [ "$CONFIRM" != "yes" ]; then
    echo "Aborted."
    exit 0
fi

echo ""
echo "=========================================="
echo "Step 1: Delete Duplicate Backend Container App"
echo "=========================================="
echo "Deleting: auditapp-backend (keeping auditapp-staging-backend)"
az containerapp delete --name auditapp-backend --resource-group $RG_NAME --yes || echo "⚠️  Already deleted or not found"
echo "✅ Done"
echo ""

echo "=========================================="
echo "Step 2: Delete Redis Cache (saves $75/month)"
echo "=========================================="
echo "Deleting: auditapp-staging-redis-wgjuafflp2o4o"
az redis delete --name auditapp-staging-redis-wgjuafflp2o4o --resource-group $RG_NAME --yes || echo "⚠️  Already deleted or not found"
echo "✅ Done - Saving $75/month!"
echo ""

echo "=========================================="
echo "Step 3: Delete Key Vault (saves $1/month)"
echo "=========================================="
echo "Deleting: kv-auditapp-wgjuafflp2"
az keyvault delete --name kv-auditapp-wgjuafflp2 --resource-group $RG_NAME --yes || echo "⚠️  Already deleted or not found"
echo "Purging Key Vault permanently..."
az keyvault purge --name kv-auditapp-wgjuafflp2 || echo "⚠️  Already purged or not found"
echo "✅ Done - Saving $1/month!"
echo ""

echo "=========================================="
echo "Step 4: Delete Old Frontend Image from ACR"
echo "=========================================="
echo "Deleting: auditapp-frontend image"
az acr repository delete --name auditappstagingacrwgjuafflp2o4o --repository auditapp-frontend --yes || echo "⚠️  Already deleted or not found"
echo "✅ Done"
echo ""

echo "=========================================="
echo "Step 5: Configure Static Web App"
echo "=========================================="
echo ""
echo "⚠️  MANUAL STEP REQUIRED:"
echo ""
echo "The Static Web App 'auditapp-staging-frontend' is NOT connected to GitHub."
echo "You need to connect it manually:"
echo ""
echo "Option A: Via Azure Portal (Recommended)"
echo "--------------------------------------------"
echo "1. Go to: https://portal.azure.com"
echo "2. Navigate to: auditapp-staging-rg → auditapp-staging-frontend"
echo "3. Click 'Deployment' in left menu"
echo "4. Click 'GitHub' and authorize"
echo "5. Select:"
echo "   - Organization: sandeeplingam1"
echo "   - Repository: Audit-App"
echo "   - Branch: main"
echo "6. Build configuration:"
echo "   - App location: /frontend"
echo "   - Api location: (leave empty)"
echo "   - Output location: dist"
echo "7. Click 'Save'"
echo ""
echo "Option B: Via CLI (Advanced)"
echo "--------------------------------------------"
echo "You need a GitHub token with 'repo' and 'workflow' permissions."
echo "Get one from: https://github.com/settings/tokens"
echo ""
echo "Then run:"
echo "az staticwebapp update \\"
echo "  --name auditapp-staging-frontend \\"
echo "  --resource-group $RG_NAME \\"
echo "  --source https://github.com/sandeeplingam1/Audit-App \\"
echo "  --branch main \\"
echo "  --app-location '/frontend' \\"
echo "  --output-location 'dist' \\"
echo "  --token YOUR_GITHUB_TOKEN"
echo ""
read -p "Press Enter after you've connected GitHub (or skip for now)..."
echo ""

echo "=========================================="
echo "Step 6: Set Frontend Environment Variable"
echo "=========================================="
BACKEND_URL=$(az containerapp show --name auditapp-staging-backend --resource-group $RG_NAME --query "properties.configuration.ingress.fqdn" -o tsv)
echo "Setting VITE_API_URL to: https://$BACKEND_URL"
az staticwebapp appsettings set \
  --name auditapp-staging-frontend \
  --resource-group $RG_NAME \
  --setting-names "VITE_API_URL=https://$BACKEND_URL"
echo "✅ Done"
echo ""

echo "=========================================="
echo "✅ Cleanup Complete!"
echo "=========================================="
echo ""
echo "💰 Monthly Savings: $76"
echo ""
echo "📊 Remaining Resources:"
az resource list --resource-group $RG_NAME --query "[].{Name:name, Type:type}" --output table
echo ""
echo "🌐 Your URLs:"
echo "Backend:  https://$BACKEND_URL"
echo "Frontend: https://$(az staticwebapp show --name auditapp-staging-frontend --resource-group $RG_NAME --query 'defaultHostname' -o tsv 2>/dev/null || echo 'pending-deployment')"
echo ""
echo "🔥 Next Steps:"
echo "1. If you haven't connected GitHub yet, do it now (see instructions above)"
echo "2. GitHub will auto-deploy your frontend when you connect"
echo "3. Test your backend: curl https://$BACKEND_URL/health"
echo "4. Wait 5-10 min for frontend deployment, then test the app"
echo ""
